### ISSUE TITLE
Determine approach for addressing article length and modify as necessary

### ISSUE THREAD

**Issue by YiMihi** [YiMihi/elm-with-jwt#14]
Determine approach for addressing article length and modify as necessary:

Options:
1. Take a different approach and assume user has some Elm experience already; can trim out syntax and typing descriptions. (I don't really recommend this approach because there is a lack of indepth tutorials for Elm beginners; I feel that doing this would reduce the value of the article.)
2. Split the tutorial up into multiple parts and position it as a way for devs new to Elm to both learn the language and also build something more realistic than "Hello, World" while doing so. (Recommended approach: there don't seem to be many/any? tutorials like this available for Elm right now aside from the official docs, which provide only one sample app with any kind of walkthrough support.)

**Comment by kmaida** [comment]
I can likely trim some length just through simple editing and possibly linking to GitHub commits instead of posting the full code for each step. I'll do these things and revisit the article length.

**Comment by YiMihi** [comment]
I trimmed some length by changing language, rephrasing sections, and removing unnecessary copy. I also replaced the full code steps with links to commits.

**Comment by YiMihi** [comment]
Split article into 2 parts
- [ ] Intro to Elm and Calling an API
- [ ] Adding Authentication

Need intro and conclusion for each part.
